apiVersion: v1
kind: Service
metadata:
  labels:
    app: realworld-app
  name: backend-service
  namespace: realworld-app
spec:
  type: LoadBalancer
  ports:
  - name: "backend-service"
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: realworld-app