apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: realworld-app
    type: be
  name: backend
  namespace: realworld-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realworld-app
  template:
    metadata:
      labels:
        app: realworld-app
    spec:
      containers:
      - image: allthethings/spring-boot-realworld-example-app
        name: backend
        ports:
        - containerPort: 8080
          name: realworld-app
