apiVersion: v1
kind: Service
metadata:
  labels:
    app: realworld-app
  name: backend-service
  namespace: realworld-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: realworld-app
    type: be